name: Selenium Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Download ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=118.0.5993.90
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          #unzip chromedriver_linux64.zip
          #chmod +x chromedriver
          #sudo mv chromedriver /usr/local/bin/chromedriver
          
        

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          chromium-browser --version
          chromedriver --version


      - name: Run Selenium tests
        run: python test.py
